
[build]
  command = "CI=false npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.19.0"
  CI = "false"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
