version: '3.8'
services:
  appwrite:
    image: appwrite/appwrite:latest
    ports:
      - "80:80"
    environment:
      - _APPWRITE_POSTGRES_HOST=appwrite-postgres
      - _APPWRITE_POSTGRES_USER=genie
      - _APPWRITE_POSTGRES_PASS=${DB_PASSWORD}
      - _APPWRITE_POSTGRES_DB=genielabs
    depends_on:
      - appwrite-postgres
  appwrite-postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: genielabs
      POSTGRES_USER: genie
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
